# Generated by Django 5.2.2 on 2025-06-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
